package com.fulei.fuleitest.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.fulei.fuleitest.greendao.GoodsWay;

import com.fulei.fuleitest.greendao.GoodsWayDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig goodsWayDaoConfig;

    private final GoodsWayDao goodsWayDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        goodsWayDaoConfig = daoConfigMap.get(GoodsWayDao.class).clone();
        goodsWayDaoConfig.initIdentityScope(type);

        goodsWayDao = new GoodsWayDao(goodsWayDaoConfig, this);

        registerDao(GoodsWay.class, goodsWayDao);
    }
    
    public void clear() {
        goodsWayDaoConfig.clearIdentityScope();
    }

    public GoodsWayDao getGoodsWayDao() {
        return goodsWayDao;
    }

}
